# Generated by Django 3.1.3 on 2021-01-02 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_date', models.DateField()),
                ('message', models.CharField(max_length=200)),
                ('prediction', models.CharField(max_length=10)),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlp_api.company')),
            ],
        ),
    ]
