# Generated by Django 3.1.4 on 2021-01-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_api', '0002_company_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='fetched_date',
            field=models.DateTimeField(),
        ),
    ]
